INSERT INTO LicenseType (ManufacturerID, LicenseTypeName)
VALUES (12, 'Photoshop'),
       (12, 'After Effects'),
       (12, 'Lightroom'),
       (12, 'Illustrator'),
       (12, 'Premiere Pro'),
       (13, 'RealFlow'),
       (13, 'Maxwell Render'),
       (13, 'XFlow'),
       (6, 'Cinema4D Studio'),
       (6, 'ZBrush'),
       (6, 'Redshift'),
       (9, 'Maya'),
       (9, '3DsMax'),
       (9, 'Arnold'),
       (10, 'Houdini');